id = "zed-tostring-extension"
name = "ToString Generator"
description = "Automatically generates a toString method for TypeScript classes."
version = "0.1.0"
schema_version = 1
authors = ["Your Name <your.email@example.com>"]
repository = "https://github.com/your-repo/zed-tostring-extension"
